// <auto-generated />
using InternetSales.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternetSales.DataAccess.Migrations
{
    [DbContext(typeof(InternetSalesContext))]
    [Migration("20231013010100_SeedInternetSalesTable")]
    partial class SeedInternetSalesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternetSales.DataAccess.Model.InternetSalesModel", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PurchasedCellService")
                        .HasColumnType("bit");

                    b.Property<bool>("PurchasedInternet")
                        .HasColumnType("bit");

                    b.Property<bool>("PurchasedPhone")
                        .HasColumnType("bit");

                    b.Property<bool>("TvService")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId");

                    b.ToTable("InternetSales");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            BusinessAddress = "123 Happy Street",
                            BusinessName = "Alltel",
                            BusinessOwner = "John Doe",
                            PurchasedCellService = false,
                            PurchasedInternet = false,
                            PurchasedPhone = false,
                            TvService = false
                        },
                        new
                        {
                            CustomerId = 2,
                            BusinessAddress = "123 Other Street",
                            BusinessName = "360 Communications",
                            BusinessOwner = "John Wilson",
                            PurchasedCellService = true,
                            PurchasedInternet = true,
                            PurchasedPhone = true,
                            TvService = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
